ansible_user: administrator
#ansible_password: "YourMostSecretPasswordButNotSoEasyAsThis!AndPleaseUncomment"
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: ntlm
